# WebUIProd Production Site Deployment Script
# Deploys to V:\sites\WebUIProd_Prod with AF_SEATPLY database

param(
    [switch]$SkipBuild = $false
)

# Configuration
$projectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$deployPath = "V:\sites\WebUIProd_Prod"
$distPath = Join-Path $projectRoot "dist"
$queriesPath = Join-Path $projectRoot "queries"

# Database Configuration for Production Environment
$dsClient = "AF_SEATPLY"
$dsClientEXT = "AF_SEATPLY_EXT"
$dbClient = "AF_SEATPLY"
$dbClientEXT = "AF_SEATPLY_EXT"
$environment = "PRODUCTION"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "WebUIProd Production Site Deployment" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Target: $deployPath" -ForegroundColor Red
Write-Host "Database: $dbClient" -ForegroundColor Red
Write-Host ""
Write-Host "WARNING: This deploys to PRODUCTION!" -ForegroundColor Red
Write-Host "Press Ctrl+C to cancel, or Enter to continue..." -ForegroundColor Red
Read-Host

Write-Host ""

# Step 1: Build the project
if (-not $SkipBuild) {
    Write-Host "[1/5] Building React app with Vite..." -ForegroundColor Green
    Push-Location $projectRoot
    npm run build
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Build failed!" -ForegroundColor Red
        exit 1
    }
    Pop-Location
    Write-Host "Build completed successfully" -ForegroundColor Green
} else {
    Write-Host "[1/5] Skipping build (--SkipBuild flag used)" -ForegroundColor Green
}

# Step 2: Create deployment directory
Write-Host "[2/5] Creating deployment directory..." -ForegroundColor Green
if (-not (Test-Path $deployPath)) {
    New-Item -ItemType Directory -Path $deployPath -Force | Out-Null
    Write-Host "Created $deployPath" -ForegroundColor Green
} else {
    Write-Host "$deployPath already exists" -ForegroundColor Green
}

# Step 3: Copy built files
Write-Host "[3/5] Copying React app to deployment directory..." -ForegroundColor Green
if (Test-Path $distPath) {
    $webPath = Join-Path $deployPath "web"
    if (Test-Path $webPath) {
        Remove-Item -Path $webPath -Recurse -Force
    }
    Copy-Item -Path $distPath -Destination $webPath -Recurse -Force
    Write-Host "React app copied to $webPath" -ForegroundColor Green
} else {
    Write-Host "ERROR: dist directory not found at $distPath" -ForegroundColor Red
    exit 1
}

# Step 4: Copy ColdFusion queries
Write-Host "[4/5] Copying ColdFusion query files..." -ForegroundColor Green
if (Test-Path $queriesPath) {
    $cfPath = Join-Path $deployPath "queries"
    if (Test-Path $cfPath) {
        Remove-Item -Path $cfPath -Recurse -Force
    }
    Copy-Item -Path $queriesPath -Destination $cfPath -Recurse -Force
    Write-Host "Query files copied to $cfPath" -ForegroundColor Green
} else {
    Write-Host "WARNING: queries directory not found at $queriesPath" -ForegroundColor Yellow
}

# Step 5: Create environment configuration file
Write-Host "[5/5] Creating environment configuration..." -ForegroundColor Green
$configContent = @"
<!--- WebUIProd Production Site Environment Configuration --->
<!--- Auto-generated by WebUIProd_ProdSite.ps1 deployment script --->
<!--- DO NOT MODIFY MANUALLY - changes will be overwritten on next deployment --->

<cfset application.environment = "$environment">
<cfset application.dsClient = "$dsClient">
<cfset application.dsClientEXT = "$dsClientEXT">
<cfset application.dbClient = "$dbClient">
<cfset application.dbClientEXT = "$dbClientEXT">
<cfset application.deployPath = "$deployPath">
<cfset application.deployTimestamp = "#DateFormat(Now(), 'YYYY-MM-DD')# #TimeFormat(Now(), 'HH:MM:SS')#">
"@

$configFile = Join-Path $deployPath "environment-config.cfm"
Set-Content -Path $configFile -Value $configContent -Encoding UTF8
Write-Host "Environment configuration created at $configFile" -ForegroundColor Green

# Summary
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Production Deployment Complete!" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Location:  $deployPath" -ForegroundColor Red
Write-Host "Database:  $dbClient" -ForegroundColor Red
Write-Host "Ext DB:    $dbClientEXT" -ForegroundColor Red
Write-Host "Web App:   $webPath" -ForegroundColor Red
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Verify ColdFusion datasources in CF Administrator" -ForegroundColor Yellow
Write-Host "2. Update web server document root to point to: $webPath" -ForegroundColor Yellow
Write-Host "3. Update CF mapping 'AUTOFAB_SEATPLY' to point to: $cfPath" -ForegroundColor Yellow
Write-Host "4. Restart ColdFusion services if needed" -ForegroundColor Yellow
Write-Host ""
